<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.e8auZAH' shared service.

return $this->privates['.service_locator.e8auZAH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'contacter' => array('privates', '.errored..service_locator.e8auZAH.App\\Entity\\Contacter', NULL, 'Cannot autowire service ".service_locator.e8auZAH": it references class "App\\Entity\\Contacter" but no such service exists.'),
));
