<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerABsWEJC\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerABsWEJC/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerABsWEJC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerABsWEJC\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerABsWEJC\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'ABsWEJC',
    'container.build_id' => '9df2eb2f',
    'container.build_time' => 1549469218,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerABsWEJC');
